### ISSUE TITLE
[Incompatability] Better Suggestions Crashes With Chat Heads Installed

### ISSUE THREAD

**Issue by JustAHuman-xD** [shurik204/better-suggestions#1]
When using Better Suggestions with Chat Heads the game crashes. Attached is the crash log & log file.
[crash-2023-05-16_16.36.52-client.txt](https://github.com/shurik204/better-suggestions/files/11492253/crash-2023-05-16_16.36.52-client.txt)
[2023-05-16-1.log.gz](https://github.com/shurik204/better-suggestions/files/11492261/2023-05-16-1.log.gz)

**Comment by shurik204** [comment]
This happens because my mod overwrites `render` method of `SuggestionWindow` and Chat Heads tries to inject there as well.
I've updated the mod so it won't crash anymore [(0.1.1)](https://modrinth.com/mod/better-suggestions/version/0.1.1). It still breaks head rendering in suggestions though.
![suggestions](https://github.com/shurik204/better-suggestions/assets/43310372/02ef39be-1103-4ae8-9b70-870be68a8c69)

I'll leave this issue open until I have more time to make a proper fix.
